version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./bookmyparking:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/bookmyparking-db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=bookmyparking-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
