# Generated by Django 5.0.3 on 2024-03-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_place', models.CharField(choices=[('M', 'Moto'), ('V', 'Voiture'), ('H', 'Handicapé')], default='V', max_length=1)),
                ('numero', models.CharField(max_length=50)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='parkings.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='places.place')),
            ],
        ),
    ]
